# run: conda env create --file environment.yml
# I've only checked with conda==4.3.25 so please update
# to this version if there's an error
name: celer-env

dependencies:
    - ipython
    - numpy>=1.12
    - seaborn>=0.7
    - scipy>=0.18.0
    - matplotlib>=2.0.0
    - Cython>=0.26
    - scikit-learn>=0.18.0
    - tqdm

    - pip:
        - "git+https://github.com/choldgraf/download"
