name: Build wheels

on: [push, pull_request]

jobs:
  build_wheels:
    name: Build wheels on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [macos-latest, windows-latest, ubuntu-latest]

    steps:
      - uses: actions/checkout@v2

      - name: Set up Python 3.8
        uses: actions/setup-python@v2
        with:
          python-version: 3.8

      - name: Upgrade pip
        run: python -m pip install --upgrade pip

      - name: Install celer
        run: |
          pip install numpy==1.21
          pip install -e .

      - name: Build source dist
        run: |
          python setup.py sdist

      - name: Install / setup cibuildwheel
        run: |
          python -m pip install cibuildwheel
          python -m cibuildwheel --output-dir wheelhouse
        env:
          CIBW_BEFORE_BUILD: pip install numpy==1.21
          CIBW_BUILD: >
            cp38-macosx_x86_64 cp38-macosx_universal2 cp38-macosx_arm64 
            cp39-macosx_x86_64 cp39-macosx_universal2 cp39-macosx_arm64 
            cp310-macosx_x86_64 cp310-macosx_universal2 cp310-macosx_arm64 
            cp38-win_amd64 cp38-win32 
            cp39-win_amd64 cp39-win32 cp39-win_arm64 
            cp38-manylinux_x86_64 cp38-manylinux_i686 
            cp39-manylinux_x86_64 cp39-manylinux_i686 
            cp310-manylinux_x86_64 cp310-manylinux_i686 

      - name: Inspect wheelhouse
        run: ls wheelhouse

      - name: publish to Test PyPI
        env:
          TWINE_USERNAME: __token__
          TWINE_PASSWORD: ${{ secrets.TEST_PYPI_API_TOKEN }}
        run: |
          pip install twine
          twine upload --repository testpypi wheelhouse/*.whl dist/*.tar.gz