name: build-many-linux-wheels

on:
  pull_request:
    branches:
      - 'main'

jobs:
  ml-wheels:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup Python 3.8
        uses: actions/setup-python@v2
        with:
          python-version: 3.8

      - name: upgrade pip & install numpy
        run: |
          python -m pip install --upgrade pip

      - name: Build source dist
        run: |
          python setup.py sdist

      - name: Build manylinux Python wheels
        uses: RalfG/python-wheels-manylinux-build@v0.4.2-manylinux2014_x86_64
        with:
          python-versions: 'cp37-cp37m cp38-cp38 cp39-cp39 cp310-cp310'
          build-requirements: 'cython numpy==1.21 scipy libsvmdata scikit-learn xarray download'

      - name: publish to Test PyPI
        env:
          TWINE_USERNAME: __token__
          TWINE_PASSWORD: ${{ secrets.TEST_PYPI_API_TOKEN }}
        run: |
          pip install twine
          twine upload --repository testpypi dist/*-manylinux*.whl dist/*.tar.gz

      # - name: publish to PyPI
      #   # if: startsWith(github.ref, 'refs/tags/release')
      #   env:
      #     TWINE_USERNAME: __token__
      #     TWINE_PASSWORD: ${{ secrets.PYPI_API_TOKEN }}
      #   run: |
      #     pip install twine
      #     twine upload dist/*-manylinux*.whl dist/*.tar.gz